---
title: "Qing Xu"
output:
  html_document:
    toc: true
    toc_float: true
---
<br>
[[Download Resume]{style="float:right"}](./link_file/resume.pdf) 
<br>
[[下载简历]{style="float:right"}](./link_file/resume_chinese.pdf) 


***

##Summary 
Skilled biostatistical programmer with 3 years of experience providing statistical analysis support and data manipulating for clinical projects in academic and industrial areas. With a master’s degree in biostatistics from Columbia University and solid skill of SAS and R software programming. Have experience in SDTM, ADaM, TFL production and validation, CRF annotation and specification updating in Clinical Phase I/II/III studies.
<br>  

   
##Education
####**Master of Science: Biostatistics**  
####Columbia University, Mailman School of Public Health [New York, NY, May 2019]{style="float:right"}
- Courses: Probability, Biostatistics methods, Statistical Inference, Data Science, Epidemiology, Survival Analysis, Analysis of Longitudinal, Design of Medical Experiment, Randomized Clinical Trial I, Randomized Clinical Trial II

- GPA: 3.77

####**Bachelor of Science: Biological Science**  
####Nanjing University[Nanjing, China, Jun 2017]{style="float:right"}
- Courses: Calculus, Linear Algebra, Introduction to Bioinformatics, Proteomics, C Programming
- GPA: 3.76
<br>  
  

##Working Experience
####**Programmer Analyst**
####PPD, part of Thermo Fisher Scientific, New Jersey, NJ [Feb 2021 – Current]{style="float:right"}                                                                
-	Produce and validate SDTM and ADaM datasets based on specification for Phase I/II/III Oncology studies  
-	Produce and validate Tables, Figures and Listings (TFL) with SAS macro, including complicate shift tables and output formats for safety and efficacy analysis
-	Generate annotated Case Report Forms (CRF) based on study protocol and SDTM specification
-	Quality control of unblinded masked and scrambling datasets, and help with data delivery
-	Update SDTM/ADaM/TFL specification based on Study protocol and datasets
-	Generate SAS macro for repeated TLF outputs

####**Biostatistical Programmer**
####Brightech International, New Jersey, NJ [Sep 2020 – Feb 2021]{style="float:right"}  
-	Generate and validate ADaM datasets and TFL based on standard operating procedures and specification in a timely manner
-	Perform statistics analysis such as chi-square test, t test, ANOVA, logistic regression, cox models and KM plots on clinical data in phase I/II/III according to statistical analysis plan with SAS software
-	Participant in SAS macro development and debugs, specification updates for Oncology and COVID studies

####**Biostatistics Data Analyst**
####Research Foundation for Mental Hygiene, New York, NY [Jun 2019 - Sep 2020]{style="float:right"}
-	Machine Learning methods and predictive models for behavior outcome prediction with longitudinal data  
-	Participate in data analysis of stratified randomized clinical trial of schizophrenia  
- Built web-based risk calculator of conversion to psychosis  
-	Collaborate with clinicians for mental health paper publication
<br>

####**Biostatistics Research Assistant**
####Columbia University/NYSPI, New York, NY [Oct 2018 - May 2019]{style="float:right"}
- Conduct propensity score matching, survival analysis and logistics regression, including building cox survival models, plot survival functions and hazard curves with R, SAS SQL and SAS macro
- Help with data cleaning and make a codebook for a large survey database with SAS, SPSS and Excel
- Collaborate with biostatistician and medical researchers for clinical trial data analysis in heart failure and mental health
<br>  

####**Research Biostatistician Intern**
####New York-Presbyterian Hospital, New York, NY [May 2018 - Aug 2018]{style="float:right"}
- Explored clinical trial data of trauma among hospitals in New York by using surveys, generalized linear models, cross correlation analysis, longitudinal data analysis, ANOVA and mapping in R
- Collaborated and consulted with surgeons and biostatisticians by contributing to the statistical design, analysis of clinical trials, and other study designs to execute trauma clinical research
- Provided analytic support for clinical and regulatory reports and research papers
<br>

##Publication
- Brucato, G., First, M., Dishy, G., Samuel, S., Xu, Q., Wall, M., . . . Girgis, R. (2021). Recency and intensification of positive symptoms enhance prediction of conversion to syndromal psychosis in clinical high-risk patients. Psychological Medicine, 51(1), 112-120. doi:10.1017/S0033291719003040       

- Budimirovic, D. B., Protic, D. D., Delahunty, C. M., Andrews, H. F., Choo, T.-H., Xu, Q., Berry-Kravis, E., Kaufmann, W. E., & for the FORWARD Consortium (2021). Sleep problems in fragile X syndrome: Cross-sectional analysis of a large clinic-based cohort. American Journal of Medical Genetics Part A, 1– 11. https://doi.org/10.1002/ajmg.a.62601

- Height and Body Mass Index in Fragile X Syndrome: A Longitudinal Assessment. Obesity. DOI: 10.1002/oby.23368

- Joseph A Gancayco, Weijia Fan, Qing Xu. (2019).  Readmission after Mitral Valve Surgery for Functional Mitral Regurgitation: Detailed Insights into Heart Failure Recurrence and Healthcare Utilization.  
<br>
  
##Skill  
- R (R shiny and R markdown)
- SAS (Base and Advanced Programmer Certifications, SAS macro and SAS SQL)
- Tableau
- SPSS
- Excel
- Chinese
